// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQWgxypq7oYyUqV7HD-axcmEnhPz-q5Bo',
    appId: '1:1078293053360:web:40ff06dd5d38da71d7e075',
    messagingSenderId: '1078293053360',
    projectId: 'd20-weather',
    authDomain: 'd20-weather.firebaseapp.com',
    storageBucket: 'd20-weather.appspot.com',
    measurementId: 'G-0KTD4PCRRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7aoBoC1xF1CIyRPHjwf4wtWogWaNg6Vo',
    appId: '1:1078293053360:android:357c5ff885c3c8f4d7e075',
    messagingSenderId: '1078293053360',
    projectId: 'd20-weather',
    storageBucket: 'd20-weather.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzDqjYR2JihK-CUxpCF-T7b7VSBrOjvr8',
    appId: '1:1078293053360:ios:0072ab413214a163d7e075',
    messagingSenderId: '1078293053360',
    projectId: 'd20-weather',
    storageBucket: 'd20-weather.appspot.com',
    iosBundleId: 'com.example.fantasyWeatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzDqjYR2JihK-CUxpCF-T7b7VSBrOjvr8',
    appId: '1:1078293053360:ios:8007902e7934fb28d7e075',
    messagingSenderId: '1078293053360',
    projectId: 'd20-weather',
    storageBucket: 'd20-weather.appspot.com',
    iosBundleId: 'com.example.fantasyWeatherApp.RunnerTests',
  );
}
